version: "3.9"
services:
  seas_mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      seas_network:
        ipv4_address: 173.20.0.100
    ports:
      - "1883:1883"
      - "9001:9001"

  seas_influxdb:
    image: influxdb:latest
    container_name: KNOWLEDGE
    restart: always
    environment:
              # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
              - DOCKER_INFLUXDB_INIT_MODE=setup
              - DOCKER_INFLUXDB_INIT_USERNAME=admin
              - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
              - DOCKER_INFLUXDB_INIT_ORG=univaq
              - DOCKER_INFLUXDB_INIT_BUCKET=seas
              - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=seasinfluxdbtoken
    networks:
       seas_network:
          ipv4_address: 173.20.0.102
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_ROOT_URL=http://172.20.0.104:3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - '3000:3000'
    networks:
      seas_network:
        ipv4_address: 173.20.0.107
    depends_on:
      - seas_influxdb
      
networks:
  seas_network:
    ipam:
      config:
        - subnet: "173.20.0.0/16"